"""upgrade users: make token unique and notnull

Revision ID: 131bcc7a6a24
Revises: f49beedc6080
Create Date: 2023-06-13 13:37:14.136914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "131bcc7a6a24"
down_revision = "f49beedc6080"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blog_users", "token", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint("user_token_unique_constraint", "blog_users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_token_unique_constraint", "blog_users", type_="unique")
    op.alter_column("blog_users", "token", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
