"""upgrade users: add archived column

Revision ID: 7ad378002ee7
Revises: e4cba89add0e
Create Date: 2023-06-09 13:04:04.704767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ad378002ee7"
down_revision = "e4cba89add0e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "archived")
    # ### end Alembic commands ###
