version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - "5672:5672"
      - "8080:15672"
    volumes:
      - rmq-data:/var/lib/rabbitmq

  maildev:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"


volumes:
  rmq-data: