"""create products table

Revision ID: 80f5af2e4698
Revises: 
Create Date: 2023-06-22 14:43:29.331293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80f5af2e4698"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
