# Use postgres/example user/password credentials
version: "3.9"

services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: pro_platform
      POSTGRES_USER: soren
      POSTGRES_PASSWORD: pass123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "9999:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready" ]
#      interval: 5s
#      timeout: 3s
#      retries: 5

volumes:
  db-data: