"""create post (Test)

Revision ID: 7cec93c1c057
Revises: d49af330ec66
Create Date: 2023-06-25 21:46:31.234685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7cec93c1c057"
down_revision = "d49af330ec66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_proj",
        sa.Column("title", sa.String(length=90), nullable=False),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("proj_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=150), nullable=True),
        sa.Column("url", sa.String(length=150), nullable=True),
        sa.Column("other_contributors", sa.String(length=150), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_proj")
    # ### end Alembic commands ###
