"""upgrade users: added bio

Revision ID: b9efc75e048c
Revises: 3db37d5d1e15
Create Date: 2023-06-09 16:49:15.392931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b9efc75e048c"
down_revision = "3db37d5d1e15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column("bio", sa.Text(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "bio")
    # ### end Alembic commands ###
