"""upgrade authors: added bio and values from users

Revision ID: 2f4794c4819d
Revises: b9efc75e048c
Create Date: 2023-06-09 16:52:12.886016

"""
from alembic import op
import sqlalchemy as sa

from models import Author, User

# revision identifiers, used by Alembic.
revision = "2f4794c4819d"
down_revision = "b9efc75e048c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_authors",
        sa.Column("bio", sa.Text(), server_default="", nullable=False),
    )
    connection = op.get_bind()

    connection.execute(
        sa.update(Author)
        .where(Author.user_id == User.id)
        .values({Author.bio: User.bio})
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_authors", "bio")
    # ### end Alembic commands ###
