"""upgrade users: add created_at column

Revision ID: fa572fa8023c
Revises: 7ad378002ee7
Create Date: 2023-06-09 13:24:15.725068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa572fa8023c"
down_revision = "7ad378002ee7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "created_at")
    # ### end Alembic commands ###
