# Use postgres/example user/password credentials
version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      CONFIG_CLASS: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://username:passwd@pg:5432/blog
    ports:
      - "8000:80"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5


  app-dev:
    build:
      dockerfile: ./Dockerfile-local
      context: ./
    environment:
      CONFIG_CLASS: DevelopmentConfig
      SQLALCHEMY_DATABASE_URI: postgresql://username:passwd@pg-dev:5432/blog
    volumes:
      - ./:/app
    ports:
      - "5050:5000"
    depends_on:
      pg-dev:
        condition: service_healthy

  pg-dev:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data-dev:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  db-data:
  db-data-dev: